name: Deploy to Vercel Workflow
run-name: ${{ github.actor }} is deploying to Vercel 🚀
on: [push]
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v3
      - name: Setup Node and install yarn
        uses: actions/setup-node@v3
        with: 
          node-version: 16
          run:  npm install -g yarn 
      - name: Install project    
        run: yarn install --frozen-lockfile
      - name: Running Tests
        run: yarn test      
      - name: Build project    
        run: yarn build
      - name: Set Env Vars on Vercel Project
        uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          teamId: ${{ secrets.VERCEL_TEAM_ID }} # optional, without will use personal
          projectName: testing-nextjs-deploy # project name in Vercel
      - name: deploy site to vercel      
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 