name: Deploy to Vercel Workflow
run-name: ${{ github.actor }} is deploying to Vercel 🚀
on: [push]
jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v3
      - name: Setup Node and install yarn
        uses: actions/setup-node@v3
        with: 
          node-version: 16
          run:  npm install -g yarn 
      - name: Install project    
        run: yarn install --frozen-lockfile
      - name: Running Tests
        run: yarn test      
      - name: Build project    
        run: yarn build
        env:
          NEXT_PUBLIC_SANITY_PROJECT_ID:  ${{ secrets.NEXT_PUBLIC_SANITY_PROJECT_ID }}
          NEXT_PUBLIC_SANITY_DATASET: ${{ secrets.NEXT_PUBLIC_SANITY_DATASET }}
      - name: Set Env Vars on Vercel Project
        uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: testing-nextjs-deploy
          vercel-args: "--confirm"
          envVariableKeys: ENV_VAR1,ENV_VAR2
        env:
          ENV_VAR1: myEnvVar1
          TARGET_ENV_VAR1: production
          TYPE_ENV_VAR1: encrypted 
          ENV_VAR2: envVar2Value
          TARGET_ENV_VAR2: preview,development
          TYPE_ENV_VAR2: plain
      - name: deploy site to vercel      
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}