name: Pushing Workflow
run-name: ${{ github.actor }} is pushing to Github 🚀
on: [push]
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v3
      - name: Setup Node and install yarn
        uses: actions/setup-node@v3
        with: 
          node-version: 16
          run:  npm install -g yarn 
      - name: Install project    
        run: yarn install --frozen-lockfile
      - name: Build project    
        run: yarn build
      - name: Running Tests
        run: yarn test      