name: Pushing Workflow
run-name: ${{ github.actor }} is pushing to Github 🚀
on: [push]
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v3
      - name: Setup Node, install and build project
        uses: actions/setup-node@v3
        with:
          node-version: 12
        - run: npm install -g yarn
        - run: yarn install --frozen-lockfile
        - run: yarn build
      - name: Running Tests    
        - run: yarn test
      - name: Finished  
        - run: echo "🚀 This job's status is ${{ job.status }}."