name: Pushing Workflow
run-name: ${{ github.actor }} is pushing to Github 🚀
on: [push]
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code 
        uses: actions/checkout@v3
      - name: Setup Node, install and build project
        uses: actions/setup-node@v3
        with: 
          node-version: 16
          run:  npm install -g yarn 
                yarn install --frozen-lockfile
                yarn build
      - name: Running Tests    
        run: yarn test